# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eba98f0634945c08efc25be158dc8ee989680b0e2f92c19f7eecf861fb4dcd6f4ca68e68b9b732bc122e2610050e987f007f62f15a709043a3eed598c4e5fee9

test:
  secret_key_base: 360e42f63ff369d47c2816433b59bd1bc97760527670ce1a024046793efbc04a4ee9aa10c2b91a6a406efea0466d0bd1a69499c94b9a44e0b4d80ccbba7a5c34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
